services:
  postgres-equipos:
    image: postgres:16-alpine
    container_name: postgres-equipos
    environment:
      POSTGRES_USER: equipos_user
      POSTGRES_PASSWORD: equipos_pass
      POSTGRES_DB: equipos
    ports:
      - '5432:5432'
    volumes:
      - postgres_equipos_data:/var/lib/postgresql/data

volumes:
  postgres_equipos_data: